apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-pod
  labels:
    app: spring-boot
spec:
  containers:
    - name: spring-boot-container
      image: ghcr.io/m88i/spring-boot-hello-world # 샘플 스프링 부트 이미지
      ports:
        - containerPort: 8080 # 스프링 부트의 기본 포트
